language: ruby
rvm:
- 2.3.5
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  
deploy:
  provider: heroku
  api_key: 
    secure: e2d93b97-f6e9-472d-9e65-435df34b0840
  app: potential-potato