language: ruby
rvm:
  - 2.3.3
cache:
- bundler
before_install:
- bundle lock --add-platform ruby
- bundle lock --add-platform x86_64-linux
- gem install -v 2.0.1 bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: e2d93b97-f6e9-472d-9e65-435df34b0840
  app: potential-potato
  on:
    repo: admo-1/potential-potato